name: Docker Demo Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-demo:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        shell: cmd
        run: docker build -t ai-devops-assistant .

      - name: Stop old container if exists
        shell: cmd
        run: docker stop ai-devops-container || echo No old container running

      - name: Remove old container if exists
        shell: cmd
        run: docker rm ai-devops-container || echo No old container to remove

      - name: Run new Docker container
        shell: cmd
        run: docker run -d --name ai-devops-container -p 8501:8501 ai-devops-assistant

      - name: Show running containers
        shell: cmd
        run: docker ps