name: Demo Deploy to D Folder

on:
  push:
    branches:
      - main

jobs:
  build-config-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build / Compile demo
        shell: cmd
        run: |
          echo Build step started...
          if not exist build mkdir build
          copy /Y demo-log.txt build\demo-log.txt
          echo Build step completed.

      - name: Add configuration
        shell: cmd
        run: |
          echo environment=demo> build\config.txt
          echo Configuration file created.

      - name: Deploy to fake server folder
        shell: cmd
        run: |
          if not exist D:\fake-server mkdir D:\fake-server
          copy /Y build\demo-log.txt D:\fake-server\demo-log.txt
          copy /Y build\config.txt D:\fake-server\config.txt
          dir D:\fake-server
          echo Files deployed to D:\fake-server